spring:
  application:
    name: growtogether-api
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/growtogether}
    username: ${POSTGRES_USER:growtogether}
    password: ${POSTGRES_PASSWORD:local_dev_password}
management:
  endpoints.web.exposure.include: health
