spring:
  application:
    name: growtogegher-api
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/growtogegher}
    username: ${POSTGRES_USER:growtogegher}
    password: ${POSTGRES_PASSWORD:local_dev_password}
management:
  endpoints.web.exposure.include: health
